Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from ocpmodels.models.model_registry import model_name_to_local_file

# OC20 model - trained on adsorption energies
checkpoint_path = model_name_to_local_file('GemNet-OC All', local_cache='/tmp/ocp_checkpoints/')

with contextlib.redirect_stdout(StringIO()) as _:
    calc = OCPCalculator(checkpoint_path=os.path.expanduser(checkpoint_path), cpu=False)
    


slab.set_calculator(calc)
slab.get_potential_energy()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[5], line 7[0m
[1;32m      4[0m checkpoint_path [38;5;241m=[39m model_name_to_local_file([38;5;124m'[39m[38;5;124mGemNet-OC All[39m[38;5;124m'[39m, local_cache[38;5;241m=[39m[38;5;124m'[39m[38;5;124m/tmp/ocp_checkpoints/[39m[38;5;124m'[39m)
[1;32m      6[0m [38;5;28;01mwith[39;00m contextlib[38;5;241m.[39mredirect_stdout(StringIO()) [38;5;28;01mas[39;00m _:
[0;32m----> 7[0m     calc [38;5;241m=[39m OCPCalculator(checkpoint_path[38;5;241m=[39m[43mos[49m[38;5;241m.[39mpath[38;5;241m.[39mexpanduser(checkpoint_path), cpu[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[1;32m     11[0m slab[38;5;241m.[39mset_calculator(calc)
[1;32m     12[0m slab[38;5;241m.[39mget_potential_energy()

[0;31mNameError[0m: name 'os' is not defined

