Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
! mv data.db full_data.db

import ase.db
import random

with ase.db.connect('full_data.db') as full_db:
  with ase.db.connect('data.db',append=False) as subset_db:

    # Select 50 random points for the subset!
    for i in random.shuffled(range(1,len(full_db)))[:50]:
      subset_db.write(full_db.get_atoms(i))

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[2], line 10[0m
[1;32m      6[0m [38;5;28;01mwith[39;00m ase[38;5;241m.[39mdb[38;5;241m.[39mconnect([38;5;124m'[39m[38;5;124mfull_data.db[39m[38;5;124m'[39m) [38;5;28;01mas[39;00m full_db:
[1;32m      7[0m   [38;5;28;01mwith[39;00m ase[38;5;241m.[39mdb[38;5;241m.[39mconnect([38;5;124m'[39m[38;5;124mdata.db[39m[38;5;124m'[39m,append[38;5;241m=[39m[38;5;28;01mFalse[39;00m) [38;5;28;01mas[39;00m subset_db:
[1;32m      8[0m 
[1;32m      9[0m     [38;5;66;03m# Select 50 random points for the subset![39;00m
[0;32m---> 10[0m     [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [43mrandom[49m[38;5;241;43m.[39;49m[43mshuffled[49m([38;5;28mrange[39m([38;5;241m1[39m,[38;5;28mlen[39m(full_db)))[:[38;5;241m50[39m]:
[1;32m     11[0m       subset_db[38;5;241m.[39mwrite(full_db[38;5;241m.[39mget_atoms(i))

[0;31mAttributeError[0m: module 'random' has no attribute 'shuffled'

